### ISSUE TITLE
Hostname and/or ip

### ISSUE THREAD

**Issue by jeliasson** [morpheus65535/oscarr#2]
I noticed that there is a validation for `Listening IP address` to make sure this is an IP-address of services like Sonarr, Radarr etc. What's the reasoning behind this? In my Docker setup, I don't necessarily know the ip-address of said service, just the service name which is resolvable in Docker.

As it's not really binding to any ip-address, I suggest renaming `Listening IP address` (and it's underlying variables and validation) to `Host` or similar. 

Cheers!

**Comment by jeliasson** [comment]
Why do Bazarr need to be binded to an ip address? (Haven't digged in the code)
When I tried, I was having problem with Plex and Radarr which seems to be validating to an ip-adress.

![Plex](https://i.imgur.com/D8e9bLD.png)
![One](https://i.imgur.com/6IeIPk7.png)

**Comment by morpheus65535** [comment]
Ok, sorry, I was thinking you were asking about Bazarr. :-)

This could be relaxed like it were in Bazarr. Thanks for the suggestion.

**Comment by morpheus65535** [comment]
Fixed in bf9e39e0f5376c6bd03d23178e817912b0d35fac
