### ISSUE TITLE
Oscarr looks for Bazarr on the same base IP as Oscarr

### ISSUE THREAD

**Issue by WallaWallaWA** [morpheus65535/oscarr#9]
It appears that Oscarr is perhaps hard-coded to look for Bazarr on the same base IP as Oscarr and thus ignores the IP settings for Bazarr.

    Bazarr settings:
    Hostname or IP address:  192.168.1.165
    Listening port: 6767
    Base URL:   /

Oscarr is on a PC at **192.168.1.169**. As per the Settings, Bazarr is on a PC at **192.168.1.165**. When the Bazarr icon is clicked, this error is returned:

    Error: 500 Internal Server Error
    Sorry, the requested URL 'http://192.168.1.169:5656/bazarr' caused an error:

    Internal Server Error
    Exception:
    SyntaxError('EOL while scanning string literal', ('<unknown>', 1, 10, "['en:force"))
    Traceback:
    Traceback (most recent call last):
      File "c:\python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
      File "c:\python27\lib\site-packages\bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
      File "c:\oscarr\oscarr.py", line 365, in bazarr
    output = template('bazarr', __file__=__file__, oscarr_version=oscarr_version, base_url=base_url, missing_list=missing_list, history_list=history_list)
      File "c:\python27\lib\site-packages\bottle.py", line 3624, in template
    return TEMPLATES[tplid].render(kwargs)
      File "c:\python27\lib\site-packages\bottle.py", line 3413, in render
    self.execute(stdout, env)
      File "c:\python27\lib\site-packages\bottle.py", line 3400, in execute
    eval(self.co, env)
      File "c:\oscarr\views\bazarr.tpl", line 89, in <module>
    subs_languages = ast.literal_eval(str(row[3]))
      File "c:\python27\lib\ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
      File "c:\python27\lib\ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
      File "<unknown>", line 1
    ['en:force
             ^
    SyntaxError: EOL while scanning string literal

Bazarr is not on 192.168.1.169, but *192.168.1.165* as listed in the settings. It appears that Oscarr is perhaps hard-coded to look for Bazarr on the same base IP as Oscarr and thus ignores the IP settings for Bazarr

**Comment by pkishino** [comment]
hmm,this works fine for me, did you press save?

**Comment by morpheus65535** [comment]
Works fine for me too. I've checked the code and it get the ip value from database and use it.

**Comment by WallaWallaWA** [comment]
Well, it still doesn't work for me. I added "http://" before the Bazarr IP and it does now try to read/load Bazarr and I get an "Unable to connect to Bazarr. Check your settings." error message. I'll continue to try different solutions; not sure why I'm getting this when it appears to work for others.  Thanks for taking a look.

**Comment by morpheus65535** [comment]
You need to put the only the IP address, not a URL.

**Comment by WallaWallaWA** [comment]
Understood. But without the http, I get the 500 error; with the http I get the "unable to connect to Bazarr" error. I have various services running on both systems, some that do interact with each other, and none of those have trouble with the different IP addresses, I can access each PC from the other, so I don't believe it's an access or authorization issue. Both PCs on Windows 10, same local network, and I'm not not using Docker.
![oscarr_bazarr_Capture](https://user-images.githubusercontent.com/15851408/67707832-71abff80-f978-11e9-88a8-ab484d69b1b2.PNG)

Later today, I'll try a fresh install to see if that works; if not, I'll install Oscarr on the 192.168.1.165 PC and see if that works.
Thanks for the follow-up. Since this doesn't appear to impact anyone else, it has to be an issue with my system configuration, so I'll only reply back here if I can get it resolved with one of the two options mentioned above.
